create table if not exists tool_types
(
    id   bigserial,
    name varchar(255),
    primary key (id)
);

create table if not exists tool_brands
(
    id   bigserial,
    name varchar(255),
    primary key (id)
);

create table if not exists tools
(
    id          bigserial,
    name        varchar(255),
    designation varchar(255),
    type_id     bigint references tool_types (id),
    brand_id    bigint references tool_brands (id),
    primary key (id)
);

create table if not exists tool_balances
(
    id              bigserial,
    tool_id         bigint references tools (id),
    current_balance int,
    min_balance     int,
    primary key (id)
);

create table if not exists issue_reports
(
    id                bigserial,
    tool_id           bigint references tools (id),
    count             int,
    route_card_number varchar(255),
    product_cipher    varchar(255),
    operation_number  varchar(255),
    workplace_number  varchar(255),
    employee_name     varchar(255),
    create_at         timestamp,
    primary key (id)
);

create table if not exists arrival_reports
(
    id           bigserial,
    order_number varchar(255),
    tool_id      bigint references tools (id),
    count        int,
    create_at    timestamp,
    primary key (id)
);

create table if not exists users
(
    id       integer generated by default as identity,
    username varchar_ignorecase(50)  not null unique,
    password varchar_ignorecase(500) not null,
    enabled  boolean                 not null
);


create table if not exists authorities
(
    username  varchar_ignorecase(50) not null,
    authority varchar_ignorecase(50) not null,
    constraint fk_authorities_users foreign key (username) references users (username)
);

create unique index ix_auth_username on authorities (username, authority);

